# Generated by Django 3.1.5 on 2021-01-25 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.moviemaster')),
            ],
        ),
    ]
