# Generated by Django 3.1.5 on 2021-01-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_setmovie_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmovie',
            name='show',
            field=models.CharField(max_length=50, verbose_name='Show Time'),
        ),
    ]
