# Generated by Django 3.1.5 on 2021-01-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20210125_1534'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviemaster',
            unique_together={('m_name', 'm_desc', 'm_image')},
        ),
        migrations.AlterUniqueTogether(
            name='setmovie',
            unique_together={('active', 'show', 'start_time', 'end_time')},
        ),
    ]
