# Generated by Django 3.1.5 on 2021-01-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20210125_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmovie',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
