# Generated by Django 3.1.5 on 2021-01-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_setmovie_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmovie',
            name='seats',
            field=models.CharField(default='', max_length=100),
        ),
    ]
