# Generated by Django 3.1.5 on 2021-02-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_user', '0002_bookedseatsmodel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedseatsmodel',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
